spring:
  application:
    name:
      GatewayLMS
  cloud:
    gateway:
      mvc:
        routes:
          - id: lbservice-route
            uri: lb://ASSIGNMENT
            predicates:
              - Path=/assignments/**
              
          - id: lbservice2-route
            uri: lb://COURSE
            predicates:
               - Path=/courses/**
               
          - id: lbservice3-route
            uri: lb://UsermanagementLMS
            predicates:
               - Path=/user/**

    discovery:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
            
server:
  port: 5555    
